version: '3.8'

services:
  footyapp-bot:
    image: ghcr.io/bignellrp/footyapp-bot:${BRANCH}
    container_name: footyapp-bot-${BRANCH}
    networks:
      - br1
    restart: always
    env_file:
      - /mnt/docker/footyapp-bot-${BRANCH}/.env
    environment:
      - TZ=UTC  # Set the container's timezone to UTC to avoid daylight saving issues

networks:
  br1:
    external: true
    name: br1