version: '3.8'

services:
  footyapp-bot:
    image: ghcr.io/bignellrp/footyapp-bot:main
    container_name: footyapp-bot-${BRANCH}
    networks:
      br0:
        ipv4_address: 192.168.0.228
    ports:
      - "80:80"
    restart: always
    env_file:
      - /mnt/docker/footyapp-bot/.env
    environment:
      - TZ=Europe/London

networks:
  br0:
    external: true
    name: br0